# Generated by Django 4.0.10 on 2023-12-28 09:19

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0002_alter_job_is_available'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2023, 12, 28, 9, 19, 17, 699056, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
